### ISSUE TITLE
Final vote canary epoch public key must be changed to a banano foundation owned key.

### ISSUE THREAD

**Issue by steampoweredtaco** [BananoCoin/banano#26]
### Summary

The canary keys to enable final votes for the network protocol are still setup for keys owned by the nano foundation and not banano foundation.  This means we can't upgrade the network protocol with the current v22 code or there is the slightest possibility nano foundation could sign a canary block on the banano chain before the network meets v22 saturation requirements.

These keys should be changed before we mark a v22 tag release and push this version to current v22 operators. The keys that need to be updated are here:  https://github.com/BananoCoin/banano/blob/master/nano/secure/common.cpp#L77

-----
A little more info about the protocol upgrade;

There is a v22 protocol canary to enable final votes for the consensus protocol that should be enabled after 80% of voting weight is on v22.  This helps with some fork edge cases (I don't have more details, but this is the nano change https://github.com/nanocurrency/nano-node/pull/3134)

### Node version

v22

### Build details

any build

### OS and version

any

### Steps to reproduce the behavior

NA

### Expected behavior

Only a primary banano developer has access to the single use case private keys to sign an epoch block for the final vote protocol upgrade.

### Actual behavior

The nano foundation private keys currently can upgrade the banano protocol for v22.

### Possible solution

Change the keys

**Comment by ghost** [comment]
fixed in v22.2 , commit 48f3dacd03696b3b32bfb363fcf3e54099aacb46
thank you for the bug report.
