### ISSUE TITLE
Your Wiki has been hacked

### ISSUE THREAD

**Issue by parg** [BananoCoin/banano#28]
### Summary

User kirniko has added download links to

https://github.com/kirniko/tdesktop/releases/tag/v3.1.9

### What problem would be solved by this feature?

User kirniko has added download links to

https://github.com/kirniko/tdesktop/releases/tag/v3.1.9

### Are there any previous requests for this feature?

User kirniko has added download links to

https://github.com/kirniko/tdesktop/releases/tag/v3.1.9

### Do you have a suggested solution?

User kirniko has added download links to

https://github.com/kirniko/tdesktop/releases/tag/v3.1.9

### If this feature is approved, would you be willing to submit a pull request with the solution?

I would

**Comment by renesq** [comment]
Thanks for notifying. I could send you a small bounty if you contacted me through one of the messengers
